# Site wide configuration

title: Digital Marketing Specialist
locale: en_GB
description: A digital marketing specialist who guarentees a return on investment.
logo: site-logo.png
search: true
url: http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Tom Davenport
  avatar: tom-davenport-speaking.jpg
  email: tom@tomdavenport.co.uk
  disqus-shortname: digitalmarketingspecialistltd
  twitter: tomdavenport
  facebook: #username
  github: tomdavenport
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: audio.tom
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: tomdavenport
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify: